#!/bin/sh
# Source tutorial run functions
. $WM_PROJECT_DIR/bin/tools/RunFunctions

application="poroElasticSolver"

runApplication blockMesh
#runApplication decomposePar
#runApplication mpirun -np 8 $application -parallel > log &
runApplication $application > log &
